name: IXPingCommand
main: IndexDev\IXPingCommand\Main
version: 1.0.0-IX
author: IndexDev
website: github.com/Indexa2
description: Running the /ping command allows you to see your ping
api: [5.0.0]
permissions:
  ixping.cmd:
    description: Allows you to use the /ping command
    default: true
